/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ecommerce

import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.Id
import javax.persistence.Persistence

class App {
    val greeting: String
        get() {
            val emFactory = Persistence.createEntityManagerFactory("ecommerce")
            val em = emFactory.createEntityManager()
            em.transaction.begin()
            val msg = Message(text = "before")
            em.persist(msg)
            em.transaction.commit()

            em.transaction.begin()
            val messages = em.createQuery("select m from Message m", Message::class.java).resultList
            messages.last().text = "after"
            em.transaction.commit()
            em.close()
            emFactory.close()

            return "Hello World to '${msg.text}'!"
        }
}

fun main() {
    println(App().greeting)
}

@Entity
class Message(
    @Id
    @GeneratedValue
    val id: Long? = null,
    var text: String,
)
